### PR TITLE
Fix root path used by some functions

### PR DESCRIPTION
**Pull request by jeongyeham**
## Why PR?
I've found that the intent of these variables, whether `String root` or `VirtualFile contentRoot`, is to get the currently open project directory.
However, because of CMake, the current project directory is compiled into modules and merged into ESP-IDF.
So in fact, it points to the root directory of the entire ESP-IDF, not the project directory we opened.
## How?
CMake's build directory is globally unique, so I found the build directory first and then got the parrent directory to find the current working directory.
Also I added some code to make it faster to index relevant directories.

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Hi, thanks for the PR! Could you please try the following version if it works correctly?
[OpenOCD + ESP32 Support for embedded development-0.3.2.jar.zip](https://github.com/ThexXTURBOXx/clion-embedded-esp32/files/12082968/OpenOCD.%2B.ESP32.Support.for.embedded.development-0.3.2.jar.zip)

**Comment by jeongyeham** [comment]
It works well!
I first checked that the command line from plugin to OpenOCD was correct.
And paths are shown as relative path.
Screenshot 2023-07-19 092328

**Comment by ThexXTURBOXx** [comment]
Thank you very much for testing! I have changed a few more things because string comparison like [this](https://github.com/ThexXTURBOXx/clion-embedded-esp32/pull/10/files#diff-735bdd567c49013890ae5365ec5b88a01934115af3abb9e1e41265abd1404ae7R263) does not work in Java. You need to use `String#equals` instead.
I will upload the new version in a few minutes

**Comment by jeongyeham** [comment]
Thanks for pointing out the syntax and grammar errors of my code, it helps me a lot when I'm learning java!

**Pull request merged**
